services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
  backend_app:
    image: task_manager_be
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      MONGODB_URL: mongodb://mongodb:27017
      JWT_SECRET: "fuego"
  frontend_app:
    image: task_manager_fe
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend_app
volumes:
  mongo_data: